%takes in messages channel cell array of structures containing time and
%values of logged data (generated by parseCsvs), and vector of CAN IDs
%returns matrix of data correlated so different channels share timestamps
%columns are timestamps, then data channels, rows are different times 

function vars = correlateMany(messages, ids)
    xVal = messages{ids(1)}.val;
    xTime = messages{ids(1)}.time;
    vars(:, 1) = xTime;
    vars(:, 2) = xVal;
    %figure
    %hold on
    for i = 2:length(ids)
        yTime = messages{ids(i)}.time;
        yPoints = messages{ids(i)}.val;
        yVal = interp1(yTime, yPoints, xTime, 'linear', 0);
        vars(:, 1 + i) = yVal;
        %plot(xVal, yVal, '.');
    end
    
end