function [fitresult, gof] = fitSin(steerTime, steerVal)
%CREATEFIT(STEERTIME,STEERVAL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : steerTime
%      Y Output: steerVal
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Sep-2017 17:38:45


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( steerTime, steerVal );

% Set up fittype and options.
ft = fittype( 'A*sind(w*t+p)', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [40 -180 0];
opts.MaxFunEvals = 10000;
opts.MaxIter = 10000;
opts.StartPoint = [0.0344 0.4387 0.3816];
opts.Upper = [80 180 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'steerVal vs. steerTime', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel steerTime
ylabel steerVal
grid on


