function y = interpolate(xgv,ygv,x)
% fuck matlab's interpolate
try
    y = ((ygv(find(xgv<=x,1,'last')+1)-ygv(find(xgv<=x,1,'last')))/...
         (xgv(find(xgv<=x,1,'last')+1)-xgv(find(xgv<=x,1,'last')))*...
         (x - xgv(find(xgv<=x,1,'last')))+ygv(find(xgv<=x,1,'last')));
catch %fuck im lazy and this^ is overflowing
    y = ((ygv(find(xgv<=x,1,'last'))-ygv(find(xgv<=x,1,'last')-1))/...
         (xgv(find(xgv<=x,1,'last'))-xgv(find(xgv<=x,1,'last')-1))*...
         (x - xgv(find(xgv<=x,1,'last')))+ygv(find(xgv<=x,1,'last')));
end
end