function [ car ] = REV1_car()
R25B_205_70_13_6 = 'GAAAAAAAAIAAAAAAAAAAKHEMAAAAAIODAAAAADBEAAILIIHEOIHELKPDBJGNICAMMIONPFODIPFCHCBEOJDCEBODPAHJAJPDPOBPGCOLPJHPIBOLKGBLAECECLBOOHPDJNAPGIAEKCKPDCLLHOLLHAMLCPBGOCOLKJEPLCNDGEMDDPNDENLFAPODLLNOIHODMNLEDDPDBFBHKJPDFBAEAMNDPPKEFBPLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFILBCDMLDKHGDBLDAAJEEBNDBHADPMNDFBOCIEAENNHKMMNLBNMLEEPLAAAAAAAANCEHIOODOJFIDKAEAAAAAAAAAAAAAAAALKFEGACEMIJHJNOLJEKOCIPLHPGBGBODIJENPMKLMLDEFNOLNENJMOPLAAAAAAAAIHKHBANDBKFPPOMLBIMGHCAMEKACDPODHKAGOOCMEMKAEFDEKAAHPHDMEIECNOOLELBLMNAMGMBLBJPDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPDAAAAAIPDAAAAAIPDAAAAAAAAAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPD';


% Build up car structure
car.name = 'REV1';
car.t   = [45.5; 47.0];
car.wb   = 60.2;
car.wdr = .51;
car.h   = 10.5;
car.w   = 414 + 150;
car.camber_static = [3; 1];
car.toe_static = [0 1];
car.camber_roll_gain = [.5; 1.0]; % [deg/deg] positive means camber loss in roll
car.camber_steer_gain = .095; % [deg/deg] this is a function of castor and kingpin
car.coeffs = R25B_205_70_13_6;
car.N_mag = .55; % LLTD percent front
car.roll_grad = 1; % deg/G
car.pressure = 12; % psi

car.steer_linear_m = .0067;

% calculations
car.a = (1-car.wdr)*car.wb; % this is longitudinal distance from rear axle to CoG
car.b = (car.wdr)*car.wb; % this is longitudinal distance from CoG to front axle

car.M = car.w / 32.2;
car.Fz_static = -0.5 * car.w .* [car.wdr; car.wdr; 1 - car.wdr; 1 - car.wdr];

% Wheel and Tire are springs in series
car.wheel_rate = [148.515; 142.857]; % [lbf/in]
car.tire_rate = 253.1; % [lbf/in]
car.ride_rate = (car.tire_rate .* car.wheel_rate) ./ (car.tire_rate + car.wheel_rate);

end

