function [ car ] = REV2_car()
R25B_180_60_10_7 = 'GAAAAAAAAIAAAAAAAAAAKHEMGGGGGGODAAAAADBEAAILIIHEBODNDMPDCKNOHBAMGEAKOHODCIDMCGBENIJJENODMGMAHKNLCAGOPBODCFAPDDODOAOOBGCEOMPMLCAEHDCMPFBEEENJKJLLJANDONKLGPKLMKNLMNMENHNDKBCPAFLLLPLAIJPLAOFMHNODHMCGCNPDBKBGKAAEKIFEABOLNOJNOFNDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANLDPOGMLLICHAEMDJGPLLBODFIFIJLODFLNJANAEGELLCPPLOMMLKOPLAAAAAAAAAFHOKLODPDKPHOAEAAAAAAAAAAAAAAAAONKMLOBENOAKJCPDBBDIEKPLLHPAFCODMHOCJHNLLDLNNEAMNFHGMACEAAAAAAAAMLFCLCNLAEAOGLLDDGMHINPLBEPBJFNLKBNLCAAMICLIBEAMOPKPOCBMIGDFFMOLOLFMFPPDOIMPEFPDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPDAAAAAIPDAAAAAIPDAAAAAAAAAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPD';
LC0_180_60_10_7  = 'GAAAAAAAAIAAAAAAAAAAKHEMGGGGGGODAAAAADBEAAILIIHECKEBILODGBJFEKAMEMPEFIODJEKEHCBEAMBGAMOLFBNBAIODCMJKILOLPLKBAJNLCFNHCACECBINAKPDPLJEKBBEFHEJCKLLCACKAFLLBMEEKPNLGGGHFCNDFFAFPAMDGCPHHAPLHAOGAFNLEKIOCDPDBGCBHKPDOKFLIMNLHAHOPKNLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKJDHOGMLGKPHHOLDPKMDFMODLMAHMIMLCDFPPFAEKIIKDFNDILNLBPNDAAAAAAAAIFKFKKODEFALEFAMAAAAAAAAAAAAAAAAPAEEFNAEALDEEJNDEFLPFIPLFNMKFDODKEPFILLLMACMCLPLIIDBFDBEAAAAAAAALBGBKMLLLPFHONLLJFMJCMPLJNJAGLODGANEDPBMIDKIMBBMLMMKIKBMLHBPCJODICLLKHBMPMCEMHPDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIPDAAAAAIPDAAAAAIPDAAAAAAAAAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPDAAAAAIPD';

% Build up car structure
car.name = 'REV2';
car.t_mean = 46;
car.t_rear_delta = 0;
car.wb   = 60.2;
car.wdr = .53;
car.h   = 11;
car.w   = 395 + 150;
car.camber_static = [-1; -1];
car.toe_static = [0 0];
car.camber_roll_gain = [-.5; -.5]; % [deg/deg] positive means camber loss in roll
car.camber_steer_gain = .05; % [deg/deg] this is a function of castor and kingpin
car.coeffs = LC0_180_60_10_7;
% car.coeffs = R25B_180_60_10_7;
car.N_mag = .53; % LLTD percent front
car.roll_grad = 1; % deg/G
car.pressure = 11; % psi

car.steer_linear_m = 1 .* .0067;
car.camber_compliance = 0.1;


% calculations


car.t   = [car.t_mean - car.t_rear_delta; car.t_mean + car.t_rear_delta];
car.a = (1-car.wdr)*car.wb; % this is longitudinal distance from rear axle to CoG
car.b = (car.wdr)*car.wb; % this is longitudinal distance from CoG to front axle

car.M = car.w / 32.2;
car.Fz_static = -0.5 * car.w .* [car.wdr; car.wdr; 1 - car.wdr; 1 - car.wdr];

% Wheel and Tire are springs in series
car.wheel_rate = [145; 140]; % [lbf/in]
car.tire_rate = 225; % [lbf/in]
car.ride_rate = (car.tire_rate .* car.wheel_rate) ./ (car.tire_rate + car.wheel_rate);


% Aero
% Some of these are driven by track calculations above
car.aero.devices = {'total'};

car.aero.total.C_l = 2.5;
car.aero.total.C_d = 1.0;
car.aero.total.area = (car.t(1) - 6)*28 + ...   % rear
                      (car.t(2) + 6)*22;        % front
car.aero.total.Cp_x = 4;
car.aero.total.Cp_z = -16;

% car.aero.devices = {'front', 'rear'};
% car.aero.front.C_l = 2.5;
% car.aero.front.C_d = 1;
% car.aero.front.span = car.t(2) + 6; %[in]
% car.aero.front.chord = 22; %[in]
% car.aero.front.area = car.aero.front.span * car.aero.front.chord;
% car.aero.front.Cp_x = 62;
% car.aero.front.Cp_z = -5;
% 
% car.aero.rear.C_l = 2.5;
% car.aero.rear.C_d = 1;
% car.aero.rear.span = car.t(1) - 7; %[in]
% car.aero.rear.chord = 28; %[in]
% car.aero.rear.area = car.aero.rear.span * car.aero.rear.chord;
% car.aero.rear.Cp_x = -25;
% car.aero.rear.Cp_z = -36;


end

